const sampleData = {
  products: [
    {
      imageId: "/beige_1.png",
      name: "Beige Classic Shirt 1",
      size: "M" as const,
      color: "beige" as const,
      price: 4999,
    },
    {
      imageId: "/beige_2.png",
      name: "Beige Classic Shirt 2",
      size: "L" as const,
      color: "beige" as const,
      price: 5299,
    },
    {
      imageId: "/beige_3.png",
      name: "Beige Classic Shirt 3",
      size: "S" as const,
      color: "beige" as const,
      price: 4599,
    },
    {
      imageId: "/blue_1.png",
      name: "Blue Casual Shirt 1",
      size: "M" as const,
      color: "blue" as const,
      price: 5999,
    },
    {
      imageId: "/blue_2.png",
      name: "Blue Casual Shirt 2",
      size: "L" as const,
      color: "blue" as const,
      price: 6299,
    },
    {
      imageId: "/blue_3.png",
      name: "Blue Casual Shirt 3",
      size: "S" as const,
      color: "blue" as const,
      price: 5799,
    },
    {
      imageId: "/green_1.png",
      name: "Green Stylish Shirt 1",
      size: "M" as const,
      color: "green" as const,
      price: 4999,
    },
    {
      imageId: "/green_2.png",
      name: "Green Stylish Shirt 2",
      size: "L" as const,
      color: "green" as const,
      price: 5199,
    },
    {
      imageId: "/green_3.png",
      name: "Green Stylish Shirt 3",
      size: "S" as const,
      color: "green" as const,
      price: 4899,
    },
    {
      imageId: "/purple_1.png",
      name: "Purple Elegant Shirt 1",
      size: "M" as const,
      color: "purple" as const,
      price: 6099,
    },
    {
      imageId: "/purple_2.png",
      name: "Purple Elegant Shirt 2",
      size: "L" as const,
      color: "purple" as const,
      price: 6299,
    },
    {
      imageId: "/purple_3.png",
      name: "Purple Elegant Shirt 3",
      size: "S" as const,
      color: "purple" as const,
      price: 5999,
    },
    {
      imageId: "/white_1.png",
      name: "White Formal Shirt 1",
      size: "M" as const,
      color: "white" as const,
      price: 5499,
    },
    {
      imageId: "/white_2.png",
      name: "White Formal Shirt 2",
      size: "L" as const,
      color: "white" as const,
      price: 5699,
    },
    {
      imageId: "/white_3.png",
      name: "White Formal Shirt 3",
      size: "S" as const,
      color: "white" as const,
      price: 5299,
    },
  ],
};

export default sampleData;
